Repository EDCD/EDMarketConnector, pull requests merged in 2023-11, with the labels that each got.

#2084 [2051] Config Files Audit
  .gitignore
  config/__init__.py
  config/darwin.py
  config/linux.py
  config/windows.py
  plugins/coriolis.py
  plugins/eddn.py
  plugins/edsm.py
  plugins/edsy.py
  plugins/inara.py
  tests/EDMCLogging.py/test_logging_classvar.py
  tests/config/_old_config.py
  tests/config/test_config.py
  tests/journal_lock.py/test_journal_lock.py
  tests/killswitch.py/test_apply.py
  tests/killswitch.py/test_killswitch.py
Labels: code cleanup

#2094 [2051] Utilities, Scripts, Workflow Audits
  .github/workflows/windows-build.yml
  docs/examples/click_counter/load.py
  docs/examples/plugintest/load.py
  plugins/edsm.py
  requirements-dev.txt
  scripts/find_localised_strings.py
  scripts/killswitch_test.py
  scripts/pip_rev_deps.py
  util/text.py
  util_ships.py
Labels: code cleanup, dependencies

#2096 Fix and standardize Settings UI
  plugins/coriolis.py
  plugins/eddn.py
  plugins/edsm.py
  plugins/inara.py
  prefs.py
Labels: enhancement, Plugins, code cleanup, ui

#2097 [2051] Update Supporting Files
  collate.py
  debug_webserver.py
  journal_lock.py
  myNotebook.py
  theme.py
  timeout_session.py
  update.py
Labels: code cleanup

#2098 [2051] Convert Pickle to Json
  build.py
  coriolis-update-files.py
  docs/Releasing.md
  edshipyard.py
  outfitting.py
  resources/modules.json
  resources/ships.json
Labels: enhancement, code cleanup, python

#2099 Add spansh as a URL provider
  build.py
  plugins/edsm.py
  plugins/spansh_core.py
Labels: enhancement, Plugins

#2100 [2051] Additional Core Files
  EDMC.py
  EDMCLogging.py
  EDMarketConnector.py
  dashboard.py
  killswitch.py
  l10n.py
  loadout.py
  protocol.py
  ttkHyperlinkLabel.py
Labels: enhancement, help wanted, code cleanup, python, ui
