Repository EDCD/EDMarketConnector, pull requests merged in 2023-12, with the labels that each got.

#2102 [2051] First Pass Remaining Files
  build.py
  companion.py
  docs/examples/click_counter/load.py
  hotkey/__init__.py
  hotkey/darwin.py
  hotkey/linux.py
  hotkey/windows.py
  monitor.py
  outfitting.py
  plug.py
  plugins/eddn.py
  prefs.py
  stats.py
Labels: code cleanup

#2108 [1843] Update URL Parameter Encoding
  companion.py
Labels: bug

#2109 [555] Move Default Registry Creation
  build.py
  config/__init__.py
  config/windows.py
  docs/Translations.md
  resources/EDMC_Installer_Config_template.txt
Labels: Installer

#2110 Broken Plugins Popup
  EDMarketConnector.py
  L10n/en.template
  coriolis-update-files.py
  plug.py
  prefs.py
Labels: enhancement, Plugins, ui

#2111 [1801] Add Warning for FDevIDs
  EDMarketConnector.py
  L10n/en.template
  build.py
  companion.py
Labels: enhancement
