Repository EDCD/EDMarketConnector, pull requests merged in 2024-06, with the labels that each got.

#2253 [2251] Fix FDevID Update Paths
  EDMarketConnector.py
  build.py
  collate.py
  companion.py
  config/__init__.py
  update.py
Labels: bug, Linux, Ready for Review

#2244 [#1469] Add Translation Push Check
  .github/workflows/push-checks.yml
  scripts/find_localised_strings.py
Labels: enhancement, Translations, devtools, github_actions, Ready for Review

#2255 Enabled DeprecationWarning by default and fixed references
  EDMCLogging.py
  EDMarketConnector.py
  config/__init__.py
  l10n.py
  myNotebook.py
  prefs.py
  requirements-dev.txt
  requirements.txt
Labels: devtools, python, Ready for Review

#2257 [2256] Allow Variable Num of Variables
  EDMarketConnector.py
Labels: bug, Ready for Review

#2258 [525] Add ChangeLog Tooling Utility
  .gitignore
  requirements-dev.txt
  scripts/build_changelog.py
Labels: devtools, Ready for Review
